languageCode:           "en"
title:                  "Dotfiles-CLI"
baseURL:                "https://zachinachshon.com/dotfiles-cli/"
canonifyURLs: true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/latest/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/latest/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/latest/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "CLI utility for managing a remote dotfiles repository."
  authors:              "Zachi Nachshon"
  social_image_path:    /docs/latest/assets/brand/dotfiles-cli-social.png
  social_logo_path:     /docs/latest/assets/brand/dotfiles-cli-social-logo.png
  google_analytics:     ""

  current_version:      "0.8.0"
  docs_version:         "latest"
  github_org:           "https://github.com/ZachiNachshon"
  repo:                 "https://github.com/ZachiNachshon/dotfiles-cli"
  twitter:              "zachinachshon"
  slack:                "https://SLACK_URL"
  blog:                 "https://zachi-nachshon.medium.com/"

  download:
    source:             "https://github.com/ZachiNachshon/dotfiles-cli/archive/v0.8.0.zip"
    dist:               "https://github.com/ZachiNachshon/dotfiles-cli/releases"

  sponsor:
    github:             "https://github.com/sponsors/ZachiNachshon"
    
  anchors:
    min: 2
    max: 5
